# Generated by Django 4.2.4 on 2023-08-29 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProd', models.CharField(max_length=30)),
                ('tipoProd', models.CharField(max_length=30)),
                ('modeloProd', models.CharField(max_length=30)),
                ('descripProd', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProv', models.CharField(max_length=30)),
                ('cuitProv', models.IntegerField(max_length=11)),
                ('emailProv', models.EmailField(max_length=254, null=True)),
                ('nroProv', models.IntegerField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('nroLegajo', models.IntegerField(max_length=4)),
            ],
        ),
    ]
