# Generated by Django 4.2.4 on 2023-08-29 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppStore', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='descripProd',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='modeloProd',
            new_name='modelo',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='nombreProd',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='tipoProd',
            new_name='tipo',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='cuitProv',
            new_name='cuit',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='emailProv',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='nombreProv',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='nroProv',
            new_name='numero',
        ),
    ]
