# Generated by Django 4.2.4 on 2023-09-23 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppStore', '0002_rename_descripprod_producto_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='cuit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='numero',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nroLegajo',
            field=models.IntegerField(),
        ),
    ]
