# Generated by Django 4.2.4 on 2023-09-23 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppStore', '0005_remove_pedido_productos_pedido_productos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='productos',
        ),
        migrations.AddField(
            model_name='pedido',
            name='productos',
            field=models.ManyToManyField(to='AppStore.producto'),
        ),
    ]
