# Generated by Django 4.2.4 on 2023-09-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppStore', '0007_alter_pedido_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
