# Generated by Django 4.2.4 on 2023-09-24 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppStore', '0009_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(max_length=150),
        ),
    ]
