# Generated by Django 4.2.4 on 2023-09-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppStore', '0010_alter_producto_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='modelo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(max_length=50),
        ),
    ]
